/**
 * COCO 2017 class names, in the index order EfficientDet-Lite returns.
 *
 * The model outputs a class index; this is the only thing that turns index 47
 * into "cup". The list must stay in exactly this order — a shifted entry would
 * silently mislabel every detection, which is the kind of bug that looks like
 * a broken model rather than a wrong array.
 *
 * Index 0 is unused in this model's output space; it is kept so indices line
 * up with the published COCO ordering rather than being off by one.
 */
export const COCO_LABELS: readonly string[] = [
  'unlabeled',
  'person',
  'bicycle',
  'car',
  'motorcycle',
  'airplane',
  'bus',
  'train',
  'truck',
  'boat',
  'traffic light',
  'fire hydrant',
  'street sign',
  'stop sign',
  'parking meter',
  'bench',
  'bird',
  'cat',
  'dog',
  'horse',
  'sheep',
  'cow',
  'elephant',
  'bear',
  'zebra',
  'giraffe',
  'hat',
  'backpack',
  'umbrella',
  'shoe',
  'eye glasses',
  'handbag',
  'tie',
  'suitcase',
  'frisbee',
  'skis',
  'snowboard',
  'sports ball',
  'kite',
  'baseball bat',
  'baseball glove',
  'skateboard',
  'surfboard',
  'tennis racket',
  'bottle',
  'plate',
  'wine glass',
  'cup',
  'fork',
  'knife',
  'spoon',
  'bowl',
  'banana',
  'apple',
  'sandwich',
  'orange',
  'broccoli',
  'carrot',
  'hot dog',
  'pizza',
  'donut',
  'cake',
  'chair',
  'couch',
  'potted plant',
  'bed',
  'mirror',
  'dining table',
  'window',
  'desk',
  'toilet',
  'door',
  'tv',
  'laptop',
  'mouse',
  'remote',
  'keyboard',
  'cell phone',
  'microwave',
  'oven',
  'toaster',
  'sink',
  'refrigerator',
  'blender',
  'book',
  'clock',
  'vase',
  'scissors',
  'teddy bear',
  'hair drier',
  'toothbrush',
];

export function labelForIndex(index: number): string {
  return COCO_LABELS[Math.round(index)] ?? 'unknown';
}
